#--------------------------------------------------------------------------------------#
# This file tracks currently logged user and various Passwords used in this repository #
#--------------------------------------------------------------------------------------#

# NOTE: Since this repository is for demonstration and learning needs passwords have been set in clear text
# NOTE: For greater security please use Vault encrypted password values

# Users sudo password of the user running Ansible on the host machine. (May Require sudoers configuration)  
sudo_password: GobbleDeGook              # PLEASE CHANGE THIS


# Username and password for used for Ansible provisioning. This user with password will be created on all VMs
ssh_user_name: 'fortknox'                # PLEASE CHANGE THIS to suit your requirements
ssh_user_pwd: 'getmeinside#086975'       # PLEASE CHANGE THIS

# Gets the name of the current user logged on to the Host 
loggedin_user: "{{lookup('env', 'USER')}}"

